<table>
    <thead>
        <tr>
            <th>Kelas</th>
            <th>Nama</th>
            <th>Code</th>
            <th>NIS</th>
            <th>Walikelas</th>
            <th>PAK_1_tp</th>
            <th>PAK_1_tgs</th>
            <th>PAK_1_tes</th>
            <th>PAK_2_tp</th>
            <th>PAK_2_tgs</th>
            <th>PAK_2_tes</th>
            <th>PAK_3_tp</th>
            <th>PAK_3_tgs</th>
            <th>PAK_3_tes</th>
            <th>PAK_4_tp</th>
            <th>PAK_4_tgs</th>
            <th>PAK_4_tes</th>
            <th>PAK_sts</th>
            <th>PKN_1_tp</th>
            <th>PKN_1_tgs</th>
            <th>PKN_1_tes</th>
            <th>PKN_2_tp</th>
            <th>PKN_2_tgs</th>
            <th>PKN_2_tes</th>
            <th>PKN_3_tp</th>
            <th>PKN_3_tgs</th>
            <th>PKN_3_tes</th>
            <th>PKN_4_tp</th>
            <th>PKN_4_tgs</th>
            <th>PKN_4_tes</th>
            <th>PKN_sts</th>
            <th>BIN_1_tp</th>
            <th>BIN_1_tgs</th>
            <th>BIN_1_tes</th>
            <th>BIN_2_tp</th>
            <th>BIN_2_tgs</th>
            <th>BIN_2_tes</th>
            <th>BIN_3_tp</th>
            <th>BIN_3_tgs</th>
            <th>BIN_3_tes</th>
            <th>BIN_4_tp</th>
            <th>BIN_4_tgs</th>
            <th>BIN_4_tes</th>
            <th>BIN_sts</th>
            <th>BIG_1_tp</th>
            <th>BIG_1_tgs</th>
            <th>BIG_1_tes</th>
            <th>BIG_2_tp</th>
            <th>BIG_2_tgs</th>
            <th>BIG_2_tes</th>
            <th>BIG_3_tp</th>
            <th>BIG_3_tgs</th>
            <th>BIG_3_tes</th>
            <th>BIG_4_tp</th>
            <th>BIG_4_tgs</th>
            <th>BIG_4_tes</th>
            <th>BIG_sts</th>
            <th>MAT_1_tp</th>
            <th>MAT_1_tgs</th>
            <th>MAT_1_tes</th>
            <th>MAT_2_tp</th>
            <th>MAT_2_tgs</th>
            <th>MAT_2_tes</th>
            <th>MAT_3_tp</th>
            <th>MAT_3_tgs</th>
            <th>MAT_3_tes</th>
            <th>MAT_4_tp</th>
            <th>MAT_4_tgs</th>
            <th>MAT_4_tes</th>
            <th>MAT_sts</th>
            <th>IPA_1_tp</th>
            <th>IPA_1_tgs</th>
            <th>IPA_1_tes</th>
            <th>IPA_2_tp</th>
            <th>IPA_2_tgs</th>
            <th>IPA_2_tes</th>
            <th>IPA_3_tp</th>
            <th>IPA_3_tgs</th>
            <th>IPA_3_tes</th>
            <th>IPA_4_tp</th>
            <th>IPA_4_tgs</th>
            <th>IPA_4_tes</th>
            <th>IPA_sts</th>
            <th>GEO_1_tp</th>
            <th>GEO_1_tgs</th>
            <th>GEO_1_tes</th>
            <th>GEO_2_tp</th>
            <th>GEO_2_tgs</th>
            <th>GEO_2_tes</th>
            <th>GEO_3_tp</th>
            <th>GEO_3_tgs</th>
            <th>GEO_3_tes</th>
            <th>GEO_4_tp</th>
            <th>GEO_4_tgs</th>
            <th>GEO_4_tes</th>
            <th>GEO_sts</th>
            <th>IPS_1_tp</th>
            <th>IPS_1_tgs</th>
            <th>IPS_1_tes</th>
            <th>IPS_2_tp</th>
            <th>IPS_2_tgs</th>
            <th>IPS_2_tes</th>
            <th>IPS_3_tp</th>
            <th>IPS_3_tgs</th>
            <th>IPS_3_tes</th>
            <th>IPS_4_tp</th>
            <th>IPS_4_tgs</th>
            <th>IPS_4_tes</th>
            <th>IPS_sts</th>
            <th>PIL_1_tp</th>
            <th>PIL_1_tgs</th>
            <th>PIL_1_tes</th>
            <th>PIL_2_tp</th>
            <th>PIL_2_tgs</th>
            <th>PIL_2_tes</th>
            <th>PIL_3_tp</th>
            <th>PIL_3_tgs</th>
            <th>PIL_3_tes</th>
            <th>PIL_4_tp</th>
            <th>PIL_4_tgs</th>
            <th>PIL_4_tes</th>
            <th>PIL_sts</th>
            <th>ORG_1_tp</th>
            <th>ORG_1_tgs</th>
            <th>ORG_1_tes</th>
            <th>ORG_2_tp</th>
            <th>ORG_2_tgs</th>
            <th>ORG_2_tes</th>
            <th>ORG_3_tp</th>
            <th>ORG_3_tgs</th>
            <th>ORG_3_tes</th>
            <th>ORG_4_tp</th>
            <th>ORG_4_tgs</th>
            <th>ORG_4_tes</th>
            <th>ORG_sts</th>
            <th>TIK_1_tp</th>
            <th>TIK_1_tgs</th>
            <th>TIK_1_tes</th>
            <th>TIK_2_tp</th>
            <th>TIK_2_tgs</th>
            <th>TIK_2_tes</th>
            <th>TIK_3_tp</th>
            <th>TIK_3_tgs</th>
            <th>TIK_3_tes</th>
            <th>TIK_4_tp</th>
            <th>TIK_4_tgs</th>
            <th>TIK_4_tes</th>
            <th>TIK_sts</th>
            <th>JWA_1_tp</th>
            <th>JWA_1_tgs</th>
            <th>JWA_1_tes</th>
            <th>JWA_2_tp</th>
            <th>JWA_2_tgs</th>
            <th>JWA_2_tes</th>
            <th>JWA_3_tp</th>
            <th>JWA_3_tgs</th>
            <th>JWA_3_tes</th>
            <th>JWA_4_tp</th>
            <th>JWA_4_tgs</th>
            <th>JWA_4_tes</th>
            <th>JWA_sts</th>
            <th>MAN_1_tp</th>
            <th>MAN_1_tgs</th>
            <th>MAN_1_tes</th>
            <th>MAN_2_tp</th>
            <th>MAN_2_tgs</th>
            <th>MAN_2_tes</th>
            <th>MAN_3_tp</th>
            <th>MAN_3_tgs</th>
            <th>MAN_3_tes</th>
            <th>MAN_4_tp</th>
            <th>MAN_4_tgs</th>
            <th>MAN_4_tes</th>
            <th>MAN_sts</th>
            <th>absensi_sakit</th>
            <th>absensi_ijin</th>
            <th>absensi_alpha</th>
            <th>catatan_ayat</th>
            <th>catatan_isi</th>
            <th>catatan_pesan</th>

        </tr>
    </thead>
    <tbody>
        @foreach($rapor as $row)
            <tr>
                <td>{{$row['kelas']}}/{{$row['absen']}}</td>
                <td>{{$row['siswa']['s_nama']}}</td>
                <td>{{$row['siswa']['s_code']}}</td>
                <td>{{$row['siswa']['s_nis']}}</td>
                <td>{{$row['rs_walikelas']}}</td>
                <td>{{$row['nilai']['PAK']['1']['TP']}}</td>
                <td>{{$row['nilai']['PAK']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PAK']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['PAK']['2']['TP']}}</td>
                <td>{{$row['nilai']['PAK']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PAK']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['PAK']['3']['TP']}}</td>
                <td>{{$row['nilai']['PAK']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PAK']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['PAK']['4']['TP']}}</td>
                <td>{{$row['nilai']['PAK']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PAK']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['PAK']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['PKN']['1']['TP']}}</td>
                <td>{{$row['nilai']['PKN']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PKN']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['PKN']['2']['TP']}}</td>
                <td>{{$row['nilai']['PKN']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PKN']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['PKN']['3']['TP']}}</td>
                <td>{{$row['nilai']['PKN']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PKN']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['PKN']['4']['TP']}}</td>
                <td>{{$row['nilai']['PKN']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PKN']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['PKN']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIN']['1']['TP']}}</td>
                <td>{{$row['nilai']['BIN']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIN']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIN']['2']['TP']}}</td>
                <td>{{$row['nilai']['BIN']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIN']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIN']['3']['TP']}}</td>
                <td>{{$row['nilai']['BIN']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIN']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIN']['4']['TP']}}</td>
                <td>{{$row['nilai']['BIN']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIN']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIN']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIG']['1']['TP']}}</td>
                <td>{{$row['nilai']['BIG']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIG']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIG']['2']['TP']}}</td>
                <td>{{$row['nilai']['BIG']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIG']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIG']['3']['TP']}}</td>
                <td>{{$row['nilai']['BIG']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIG']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIG']['4']['TP']}}</td>
                <td>{{$row['nilai']['BIG']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['BIG']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['BIG']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAT']['1']['TP']}}</td>
                <td>{{$row['nilai']['MAT']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAT']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAT']['2']['TP']}}</td>
                <td>{{$row['nilai']['MAT']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAT']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAT']['3']['TP']}}</td>
                <td>{{$row['nilai']['MAT']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAT']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAT']['4']['TP']}}</td>
                <td>{{$row['nilai']['MAT']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAT']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAT']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['FIS']['1']['TP']}}</td>
                <td>{{$row['nilai']['FIS']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['FIS']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['FIS']['2']['TP']}}</td>
                <td>{{$row['nilai']['FIS']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['FIS']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['FIS']['3']['TP']}}</td>
                <td>{{$row['nilai']['FIS']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['FIS']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['FIS']['4']['TP']}}</td>
                <td>{{$row['nilai']['FIS']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['FIS']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['FIS']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['GEO']['1']['TP']}}</td>
                <td>{{$row['nilai']['GEO']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['GEO']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['GEO']['2']['TP']}}</td>
                <td>{{$row['nilai']['GEO']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['GEO']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['GEO']['3']['TP']}}</td>
                <td>{{$row['nilai']['GEO']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['GEO']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['GEO']['4']['TP']}}</td>
                <td>{{$row['nilai']['GEO']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['GEO']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['GEO']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['EKO']['1']['TP']}}</td>
                <td>{{$row['nilai']['EKO']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['EKO']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['EKO']['2']['TP']}}</td>
                <td>{{$row['nilai']['EKO']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['EKO']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['EKO']['3']['TP']}}</td>
                <td>{{$row['nilai']['EKO']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['EKO']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['EKO']['4']['TP']}}</td>
                <td>{{$row['nilai']['EKO']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['EKO']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['EKO']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['PIL']['1']['TP']}}</td>
                <td>{{$row['nilai']['PIL']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PIL']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['PIL']['2']['TP']}}</td>
                <td>{{$row['nilai']['PIL']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PIL']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['PIL']['3']['TP']}}</td>
                <td>{{$row['nilai']['PIL']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PIL']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['PIL']['4']['TP']}}</td>
                <td>{{$row['nilai']['PIL']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['PIL']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['PIL']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['ORG']['1']['TP']}}</td>
                <td>{{$row['nilai']['ORG']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['ORG']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['ORG']['2']['TP']}}</td>
                <td>{{$row['nilai']['ORG']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['ORG']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['ORG']['3']['TP']}}</td>
                <td>{{$row['nilai']['ORG']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['ORG']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['ORG']['4']['TP']}}</td>
                <td>{{$row['nilai']['ORG']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['ORG']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['ORG']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['TIK']['1']['TP']}}</td>
                <td>{{$row['nilai']['TIK']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['TIK']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['TIK']['2']['TP']}}</td>
                <td>{{$row['nilai']['TIK']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['TIK']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['TIK']['3']['TP']}}</td>
                <td>{{$row['nilai']['TIK']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['TIK']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['TIK']['4']['TP']}}</td>
                <td>{{$row['nilai']['TIK']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['TIK']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['TIK']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['JWA']['1']['TP']}}</td>
                <td>{{$row['nilai']['JWA']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['JWA']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['JWA']['2']['TP']}}</td>
                <td>{{$row['nilai']['JWA']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['JWA']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['JWA']['3']['TP']}}</td>
                <td>{{$row['nilai']['JWA']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['JWA']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['JWA']['4']['TP']}}</td>
                <td>{{$row['nilai']['JWA']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['JWA']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['JWA']['STS']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAN']['1']['TP']}}</td>
                <td>{{$row['nilai']['MAN']['1']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAN']['1']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAN']['2']['TP']}}</td>
                <td>{{$row['nilai']['MAN']['2']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAN']['2']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAN']['3']['TP']}}</td>
                <td>{{$row['nilai']['MAN']['3']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAN']['3']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAN']['4']['TP']}}</td>
                <td>{{$row['nilai']['MAN']['4']['ns_tugas']}}</td>
                <td>{{$row['nilai']['MAN']['4']['ns_tes']}}</td>
                <td>{{$row['nilai']['MAN']['STS']['ns_tes']}}</td>
                <td>{{$row['rs_absensi_sakit']}}</td>
                <td>{{$row['rs_absensi_ijin']}}</td>
                <td>{{$row['rs_absensi_alpha']}}</td>
                <td>{{$row['rs_catatan_ayat']}}</td>
                <td>{{$row['rs_catatan_isi']}}</td>
                <td>{{$row['rs_catatan_pesan']}}</td>
            </tr>
        @endforeach
    </tbody>
</table>
