<table>
    <thead>
        <tr>
            <th>Kelas</th>
            <th>Nama</th>
            <th>Code</th>
            <th>NIS</th>
            <th>Walikelas</th>
            <th>spiritual_nilai</th>
            <th>spiritual_predikat</th>
            <th>spiritual_deskripsi</th>
            <th>sosial_nilai</th>
            <th>sosial_predikat</th>
            <th>sosial_deskripsi</th>
            <th>pak_uh1</th>
            <th>pak_uh2</th>
            <th>pak_uh3</th>
            <th>pak_tgs1</th>
            <th>pak_tgs2</th>
            <th>pak_tgs3</th>
            <th>pak_pts</th>
            <th>pak_prk</th>
            <th>pak_prd</th>
            <th>pak_pry</th>
            <th>pak_prt</th>
            <th>pkn_uh1</th>
            <th>pkn_uh2</th>
            <th>pkn_uh3</th>
            <th>pkn_tgs1</th>
            <th>pkn_tgs2</th>
            <th>pkn_tgs3</th>
            <th>pkn_pts</th>
            <th>pkn_prk</th>
            <th>pkn_prd</th>
            <th>pkn_pry</th>
            <th>pkn_prt</th>
            <th>bin_uh1</th>
            <th>bin_uh2</th>
            <th>bin_uh3</th>
            <th>bin_tgs1</th>
            <th>bin_tgs2</th>
            <th>bin_tgs3</th>
            <th>bin_pts</th>
            <th>bin_prk</th>
            <th>bin_prd</th>
            <th>bin_pry</th>
            <th>bin_prt</th>
            <th>big_uh1</th>
            <th>big_uh2</th>
            <th>big_uh3</th>
            <th>big_tgs1</th>
            <th>big_tgs2</th>
            <th>big_tgs3</th>
            <th>big_pts</th>
            <th>big_prk</th>
            <th>big_prd</th>
            <th>big_pry</th>
            <th>big_prt</th>
            <th>mat_uh1</th>
            <th>mat_uh2</th>
            <th>mat_uh3</th>
            <th>mat_tgs1</th>
            <th>mat_tgs2</th>
            <th>mat_tgs3</th>
            <th>mat_pts</th>
            <th>mat_prk</th>
            <th>mat_prd</th>
            <th>mat_pry</th>
            <th>mat_prt</th>
            <th>bio_uh1</th>
            <th>bio_uh2</th>
            <th>bio_uh3</th>
            <th>bio_tgs1</th>
            <th>bio_tgs2</th>
            <th>bio_tgs3</th>
            <th>bio_pts</th>
            <th>bio_prk</th>
            <th>bio_prd</th>
            <th>bio_pry</th>
            <th>bio_prt</th>
            <th>fis_uh1</th>
            <th>fis_uh2</th>
            <th>fis_uh3</th>
            <th>fis_tgs1</th>
            <th>fis_tgs2</th>
            <th>fis_tgs3</th>
            <th>fis_pts</th>
            <th>fis_prk</th>
            <th>fis_prd</th>
            <th>fis_pry</th>
            <th>fis_prt</th>
            <th>geo_uh1</th>
            <th>geo_uh2</th>
            <th>geo_uh3</th>
            <th>geo_tgs1</th>
            <th>geo_tgs2</th>
            <th>geo_tgs3</th>
            <th>geo_pts</th>
            <th>geo_prk</th>
            <th>geo_prd</th>
            <th>geo_pry</th>
            <th>geo_prt</th>
            <th>eko_uh1</th>
            <th>eko_uh2</th>
            <th>eko_uh3</th>
            <th>eko_tgs1</th>
            <th>eko_tgs2</th>
            <th>eko_tgs3</th>
            <th>eko_pts</th>
            <th>eko_prk</th>
            <th>eko_prd</th>
            <th>eko_pry</th>
            <th>eko_prt</th>
            <th>sej_uh1</th>
            <th>sej_uh2</th>
            <th>sej_uh3</th>
            <th>sej_tgs1</th>
            <th>sej_tgs2</th>
            <th>sej_tgs3</th>
            <th>sej_pts</th>
            <th>sej_prk</th>
            <th>sej_prd</th>
            <th>sej_pry</th>
            <th>sej_prt</th>
            <th>snr_uh1</th>
            <th>snr_uh2</th>
            <th>snr_uh3</th>
            <th>snr_tgs1</th>
            <th>snr_tgs2</th>
            <th>snr_tgs3</th>
            <th>snr_pts</th>
            <th>snr_prk</th>
            <th>snr_prd</th>
            <th>snr_pry</th>
            <th>snr_prt</th>
            <th>snm_uh1</th>
            <th>snm_uh2</th>
            <th>snm_uh3</th>
            <th>snm_tgs1</th>
            <th>snm_tgs2</th>
            <th>snm_tgs3</th>
            <th>snm_pts</th>
            <th>snm_prk</th>
            <th>snm_prd</th>
            <th>snm_pry</th>
            <th>snm_prt</th>
            <th>org_uh1</th>
            <th>org_uh2</th>
            <th>org_uh3</th>
            <th>org_tgs1</th>
            <th>org_tgs2</th>
            <th>org_tgs3</th>
            <th>org_pts</th>
            <th>org_prk</th>
            <th>org_prd</th>
            <th>org_pry</th>
            <th>org_prt</th>
            <th>pky_uh1</th>
            <th>pky_uh2</th>
            <th>pky_uh3</th>
            <th>pky_tgs1</th>
            <th>pky_tgs2</th>
            <th>pky_tgs3</th>
            <th>pky_pts</th>
            <th>pky_prk</th>
            <th>pky_prd</th>
            <th>pky_pry</th>
            <th>pky_prt</th>
            <th>jwa_uh1</th>
            <th>jwa_uh2</th>
            <th>jwa_uh3</th>
            <th>jwa_tgs1</th>
            <th>jwa_tgs2</th>
            <th>jwa_tgs3</th>
            <th>jwa_pts</th>
            <th>jwa_prk</th>
            <th>jwa_prd</th>
            <th>jwa_pry</th>
            <th>jwa_prt</th>
            <th>man_uh1</th>
            <th>man_uh2</th>
            <th>man_uh3</th>
            <th>man_tgs1</th>
            <th>man_tgs2</th>
            <th>man_tgs3</th>
            <th>man_pts</th>
            <th>man_prk</th>
            <th>man_prd</th>
            <th>man_pry</th>
            <th>man_prt</th>
            <th>absensi_sakit</th>
            <th>absensi_ijin</th>
            <th>absensi_alpha</th>
            <th>catatan_ayat</th>
            <th>catatan_isi</th>
            <th>catatan_pesan</th>

        </tr>
    </thead>
    <tbody>
        @foreach($rapor as $row)
            <tr>
                <td>{{$row['kelas']}} / {{$row['absen']}}</td>
                <td>{{$row['siswa']['s_nama']}}</td>
                <td>{{$row['siswa']['s_code']}}</td>
                <td>{{$row['siswa']['s_nis']}}</td>
                <td>{{$row['rs_walikelas']}}</td>
                <td>{{$row['rs_spiritual_nilai']}}</td>
                <td>{{$row['rs_spiritual_predikat']}}</td>
                <td>{{ucfirst($row['rs_spiritual_deskripsi'])}}.</td>
                <td>{{$row['rs_sosial_nilai']}}</td>
                <td>{{$row['rs_sosial_predikat']}}</td>
                <td>{{ucfirst($row['rs_sosial_deskripsi'])}}.</td>
                <td>{{$row['rs_pak_uh1']}}</td>
                <td>{{$row['rs_pak_uh2']}}</td>
                <td>{{$row['rs_pak_uh3']}}</td>
                <td>{{$row['rs_pak_tgs1']}}</td>
                <td>{{$row['rs_pak_tgs2']}}</td>
                <td>{{$row['rs_pak_tgs3']}}</td>
                <td>{{$row['rs_pak_pts']}}</td>
                <td>{{$row['rs_pak_prk']}}</td>
                <td>{{$row['rs_pak_prd']}}</td>
                <td>{{$row['rs_pak_pry']}}</td>
                <td>{{$row['rs_pak_prt']}}</td>
                <td>{{$row['rs_pkn_uh1']}}</td>
                <td>{{$row['rs_pkn_uh2']}}</td>
                <td>{{$row['rs_pkn_uh3']}}</td>
                <td>{{$row['rs_pkn_tgs1']}}</td>
                <td>{{$row['rs_pkn_tgs2']}}</td>
                <td>{{$row['rs_pkn_tgs3']}}</td>
                <td>{{$row['rs_pkn_pts']}}</td>
                <td>{{$row['rs_pkn_prk']}}</td>
                <td>{{$row['rs_pkn_prd']}}</td>
                <td>{{$row['rs_pkn_pry']}}</td>
                <td>{{$row['rs_pkn_prt']}}</td>
                <td>{{$row['rs_bin_uh1']}}</td>
                <td>{{$row['rs_bin_uh2']}}</td>
                <td>{{$row['rs_bin_uh3']}}</td>
                <td>{{$row['rs_bin_tgs1']}}</td>
                <td>{{$row['rs_bin_tgs2']}}</td>
                <td>{{$row['rs_bin_tgs3']}}</td>
                <td>{{$row['rs_bin_pts']}}</td>
                <td>{{$row['rs_bin_prk']}}</td>
                <td>{{$row['rs_bin_prd']}}</td>
                <td>{{$row['rs_bin_pry']}}</td>
                <td>{{$row['rs_bin_prt']}}</td>
                <td>{{$row['rs_big_uh1']}}</td>
                <td>{{$row['rs_big_uh2']}}</td>
                <td>{{$row['rs_big_uh3']}}</td>
                <td>{{$row['rs_big_tgs1']}}</td>
                <td>{{$row['rs_big_tgs2']}}</td>
                <td>{{$row['rs_big_tgs3']}}</td>
                <td>{{$row['rs_big_pts']}}</td>
                <td>{{$row['rs_big_prk']}}</td>
                <td>{{$row['rs_big_prd']}}</td>
                <td>{{$row['rs_big_pry']}}</td>
                <td>{{$row['rs_big_prt']}}</td>
                <td>{{$row['rs_mat_uh1']}}</td>
                <td>{{$row['rs_mat_uh2']}}</td>
                <td>{{$row['rs_mat_uh3']}}</td>
                <td>{{$row['rs_mat_tgs1']}}</td>
                <td>{{$row['rs_mat_tgs2']}}</td>
                <td>{{$row['rs_mat_tgs3']}}</td>
                <td>{{$row['rs_mat_pts']}}</td>
                <td>{{$row['rs_mat_prk']}}</td>
                <td>{{$row['rs_mat_prd']}}</td>
                <td>{{$row['rs_mat_pry']}}</td>
                <td>{{$row['rs_mat_prt']}}</td>
                <td>{{$row['rs_bio_uh1']}}</td>
                <td>{{$row['rs_bio_uh2']}}</td>
                <td>{{$row['rs_bio_uh3']}}</td>
                <td>{{$row['rs_bio_tgs1']}}</td>
                <td>{{$row['rs_bio_tgs2']}}</td>
                <td>{{$row['rs_bio_tgs3']}}</td>
                <td>{{$row['rs_bio_pts']}}</td>
                <td>{{$row['rs_bio_prk']}}</td>
                <td>{{$row['rs_bio_prd']}}</td>
                <td>{{$row['rs_bio_pry']}}</td>
                <td>{{$row['rs_bio_prt']}}</td>
                <td>{{$row['rs_fis_uh1']}}</td>
                <td>{{$row['rs_fis_uh2']}}</td>
                <td>{{$row['rs_fis_uh3']}}</td>
                <td>{{$row['rs_fis_tgs1']}}</td>
                <td>{{$row['rs_fis_tgs2']}}</td>
                <td>{{$row['rs_fis_tgs3']}}</td>
                <td>{{$row['rs_fis_pts']}}</td>
                <td>{{$row['rs_fis_prk']}}</td>
                <td>{{$row['rs_fis_prd']}}</td>
                <td>{{$row['rs_fis_pry']}}</td>
                <td>{{$row['rs_fis_prt']}}</td>
                <td>{{$row['rs_geo_uh1']}}</td>
                <td>{{$row['rs_geo_uh2']}}</td>
                <td>{{$row['rs_geo_uh3']}}</td>
                <td>{{$row['rs_geo_tgs1']}}</td>
                <td>{{$row['rs_geo_tgs2']}}</td>
                <td>{{$row['rs_geo_tgs3']}}</td>
                <td>{{$row['rs_geo_pts']}}</td>
                <td>{{$row['rs_geo_prk']}}</td>
                <td>{{$row['rs_geo_prd']}}</td>
                <td>{{$row['rs_geo_pry']}}</td>
                <td>{{$row['rs_geo_prt']}}</td>
                <td>{{$row['rs_eko_uh1']}}</td>
                <td>{{$row['rs_eko_uh2']}}</td>
                <td>{{$row['rs_eko_uh3']}}</td>
                <td>{{$row['rs_eko_tgs1']}}</td>
                <td>{{$row['rs_eko_tgs2']}}</td>
                <td>{{$row['rs_eko_tgs3']}}</td>
                <td>{{$row['rs_eko_pts']}}</td>
                <td>{{$row['rs_eko_prk']}}</td>
                <td>{{$row['rs_eko_prd']}}</td>
                <td>{{$row['rs_eko_pry']}}</td>
                <td>{{$row['rs_eko_prt']}}</td>
                <td>{{$row['rs_sej_uh1']}}</td>
                <td>{{$row['rs_sej_uh2']}}</td>
                <td>{{$row['rs_sej_uh3']}}</td>
                <td>{{$row['rs_sej_tgs1']}}</td>
                <td>{{$row['rs_sej_tgs2']}}</td>
                <td>{{$row['rs_sej_tgs3']}}</td>
                <td>{{$row['rs_sej_pts']}}</td>
                <td>{{$row['rs_sej_prk']}}</td>
                <td>{{$row['rs_sej_prd']}}</td>
                <td>{{$row['rs_sej_pry']}}</td>
                <td>{{$row['rs_sej_prt']}}</td>
                <td>{{$row['rs_snr_uh1']}}</td>
                <td>{{$row['rs_snr_uh2']}}</td>
                <td>{{$row['rs_snr_uh3']}}</td>
                <td>{{$row['rs_snr_tgs1']}}</td>
                <td>{{$row['rs_snr_tgs2']}}</td>
                <td>{{$row['rs_snr_tgs3']}}</td>
                <td>{{$row['rs_snr_pts']}}</td>
                <td>{{$row['rs_snr_prk']}}</td>
                <td>{{$row['rs_snr_prd']}}</td>
                <td>{{$row['rs_snr_pry']}}</td>
                <td>{{$row['rs_snr_prt']}}</td>
                <td>{{$row['rs_snm_uh1']}}</td>
                <td>{{$row['rs_snm_uh2']}}</td>
                <td>{{$row['rs_snm_uh3']}}</td>
                <td>{{$row['rs_snm_tgs1']}}</td>
                <td>{{$row['rs_snm_tgs2']}}</td>
                <td>{{$row['rs_snm_tgs3']}}</td>
                <td>{{$row['rs_snm_pts']}}</td>
                <td>{{$row['rs_snm_prk']}}</td>
                <td>{{$row['rs_snm_prd']}}</td>
                <td>{{$row['rs_snm_pry']}}</td>
                <td>{{$row['rs_snm_prt']}}</td>
                <td>{{$row['rs_org_uh1']}}</td>
                <td>{{$row['rs_org_uh2']}}</td>
                <td>{{$row['rs_org_uh3']}}</td>
                <td>{{$row['rs_org_tgs1']}}</td>
                <td>{{$row['rs_org_tgs2']}}</td>
                <td>{{$row['rs_org_tgs3']}}</td>
                <td>{{$row['rs_org_pts']}}</td>
                <td>{{$row['rs_org_prk']}}</td>
                <td>{{$row['rs_org_prd']}}</td>
                <td>{{$row['rs_org_pry']}}</td>
                <td>{{$row['rs_org_prt']}}</td>
                <td>{{$row['rs_pky_uh1']}}</td>
                <td>{{$row['rs_pky_uh2']}}</td>
                <td>{{$row['rs_pky_uh3']}}</td>
                <td>{{$row['rs_pky_tgs1']}}</td>
                <td>{{$row['rs_pky_tgs2']}}</td>
                <td>{{$row['rs_pky_tgs3']}}</td>
                <td>{{$row['rs_pky_pts']}}</td>
                <td>{{$row['rs_pky_prk']}}</td>
                <td>{{$row['rs_pky_prd']}}</td>
                <td>{{$row['rs_pky_pry']}}</td>
                <td>{{$row['rs_pky_prt']}}</td>
                <td>{{$row['rs_jwa_uh1']}}</td>
                <td>{{$row['rs_jwa_uh2']}}</td>
                <td>{{$row['rs_jwa_uh3']}}</td>
                <td>{{$row['rs_jwa_tgs1']}}</td>
                <td>{{$row['rs_jwa_tgs2']}}</td>
                <td>{{$row['rs_jwa_tgs3']}}</td>
                <td>{{$row['rs_jwa_pts']}}</td>
                <td>{{$row['rs_jwa_prk']}}</td>
                <td>{{$row['rs_jwa_prd']}}</td>
                <td>{{$row['rs_jwa_pry']}}</td>
                <td>{{$row['rs_jwa_prt']}}</td>
                <td>{{$row['rs_man_uh1']}}</td>
                <td>{{$row['rs_man_uh2']}}</td>
                <td>{{$row['rs_man_uh3']}}</td>
                <td>{{$row['rs_man_tgs1']}}</td>
                <td>{{$row['rs_man_tgs2']}}</td>
                <td>{{$row['rs_man_tgs3']}}</td>
                <td>{{$row['rs_man_pts']}}</td>
                <td>{{$row['rs_man_prk']}}</td>
                <td>{{$row['rs_man_prd']}}</td>
                <td>{{$row['rs_man_pry']}}</td>
                <td>{{$row['rs_man_prt']}}</td>
                <td>{{$row['rs_absensi_sakit']?$row['rs_absensi_sakit']:'-'}}</td>
                <td>{{$row['rs_absensi_ijin']?$row['rs_absensi_ijin']:'-'}}</td>
                <td>{{$row['rs_absensi_alpha']?$row['rs_absensi_alpha']:'-'}}</td>
                <td>{{$row['rs_catatan_ayat']}}</td>
                <td>{{$row['rs_catatan_isi']}}</td>
                <td>{{$row['rs_catatan_pesan']}}</td>
            </tr>
        @endforeach
    </tbody>
</table>
