<table>
    <thead>
        <tr>
            <th>Kelas</th>
            <th>Nama</th>
            <th>Code</th>
            <th>NISN</th>
            <th>NIS</th>
            <th>Walikelas</th>
            <th>spiritual_predikat</th>
            <th>spiritual_deskripsi</th>
            <th>sosial_predikat</th>
            <th>sosial_deskripsi</th>
            <th>pak_ki3_nilai</th>
            <th>pak_ki3_predikat</th>
            <th>pak_ki3_deskripsi</th>
            <th>pak_ki4_nilai</th>
            <th>pak_ki4_predikat</th>
            <th>pak_ki4_deskripsi</th>
            <th>pkn_ki3_nilai</th>
            <th>pkn_ki3_predikat</th>
            <th>pkn_ki3_deskripsi</th>
            <th>pkn_ki4_nilai</th>
            <th>pkn_ki4_predikat</th>
            <th>pkn_ki4_deskripsi</th>
            <th>bin_ki3_nilai</th>
            <th>bin_ki3_predikat</th>
            <th>bin_ki3_deskripsi</th>
            <th>bin_ki4_nilai</th>
            <th>bin_ki4_predikat</th>
            <th>bin_ki4_deskripsi</th>
            <th>mat_ki3_nilai</th>
            <th>mat_ki3_predikat</th>
            <th>mat_ki3_deskripsi</th>
            <th>mat_ki4_nilai</th>
            <th>mat_ki4_predikat</th>
            <th>mat_ki4_deskripsi</th>
            <th>ipa_ki3_nilai</th>
            <th>ipa_ki3_predikat</th>
            <th>ipa_ki3_deskripsi</th>
            <th>ipa_ki4_nilai</th>
            <th>ipa_ki4_predikat</th>
            <th>ipa_ki4_deskripsi</th>
            <th>ips_ki3_nilai</th>
            <th>ips_ki3_predikat</th>
            <th>ips_ki3_deskripsi</th>
            <th>ips_ki4_nilai</th>
            <th>ips_ki4_predikat</th>
            <th>ips_ki4_deskripsi</th>
            <th>big_ki3_nilai</th>
            <th>big_ki3_predikat</th>
            <th>big_ki3_deskripsi</th>
            <th>big_ki4_nilai</th>
            <th>big_ki4_predikat</th>
            <th>big_ki4_deskripsi</th>
            <th>bdy_ki3_nilai</th>
            <th>bdy_ki3_predikat</th>
            <th>bdy_ki3_deskripsi</th>
            <th>bdy_ki4_nilai</th>
            <th>bdy_ki4_predikat</th>
            <th>bdy_ki4_deskripsi</th>
            <th>org_ki3_nilai</th>
            <th>org_ki3_predikat</th>
            <th>org_ki3_deskripsi</th>
            <th>org_ki4_nilai</th>
            <th>org_ki4_predikat</th>
            <th>org_ki4_deskripsi</th>
            <th>pky_ki3_nilai</th>
            <th>pky_ki3_predikat</th>
            <th>pky_ki3_deskripsi</th>
            <th>pky_ki4_nilai</th>
            <th>pky_ki4_predikat</th>
            <th>pky_ki4_deskripsi</th>
            <th>jwa_ki3_nilai</th>
            <th>jwa_ki3_predikat</th>
            <th>jwa_ki3_deskripsi</th>
            <th>jwa_ki4_nilai</th>
            <th>jwa_ki4_predikat</th>
            <th>jwa_ki4_deskripsi</th>
            <th>man_ki3_nilai</th>
            <th>man_ki3_predikat</th>
            <th>man_ki3_deskripsi</th>
            <th>man_ki4_nilai</th>
            <th>man_ki4_predikat</th>
            <th>man_ki4_deskripsi</th>
            <th>ekstra1_kegiatan</th>
            <th>ekstra1_nilai</th>
            <th>ekstra1_predikat</th>
            <th>ekstra2_kegiatan</th>
            <th>ekstra2_nilai</th>
            <th>ekstra2_predikat</th>
            <th>ekstra3_kegiatan</th>
            <th>ekstra3_nilai</th>
            <th>ekstra3_predikat</th>
            <th>catatan_sakit</th>
            <th>catatan_ijin</th>
            <th>catatan_alpha</th>
            <th>catatan_ayat</th>
            <th>catatan_isi</th>
            <th>catatan_pesan</th>

        </tr>
    </thead>
    <tbody>
        @foreach($rapor as $row)
            <tr>
                <td>{{$row['kelas']}}/{{$row['absen']}}</td>
                <td>{{$row['siswa']['s_nama']}}</td>
                <td>{{$row['siswa']['s_code']}}</td>
                <td>{{$row['siswa']['s_nisn']}}</td>
                <td>{{$row['siswa']['s_nis']}}</td>
                <td>{{$row['ra_walikelas']}}</td>
                <td>{{$row['ra_spiritual_predikat']}}</td>
                <td>{{$row['ra_spiritual_deskripsi']}}</td>
                <td>{{$row['ra_sosial_predikat']}}</td>
                <td>{{$row['ra_sosial_deskripsi']}}</td>
                <td>{{$row['ra_pak_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_pak_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_pak_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_pak_keterampilan_nilai']}}</td>
                <td>{{$row['ra_pak_keterampilan_predikat']}}</td>
                <td>{{$row['ra_pak_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_pkn_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_pkn_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_pkn_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_pkn_keterampilan_nilai']}}</td>
                <td>{{$row['ra_pkn_keterampilan_predikat']}}</td>
                <td>{{$row['ra_pkn_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_bin_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_bin_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_bin_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_bin_keterampilan_nilai']}}</td>
                <td>{{$row['ra_bin_keterampilan_predikat']}}</td>
                <td>{{$row['ra_bin_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_mat_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_mat_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_mat_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_mat_keterampilan_nilai']}}</td>
                <td>{{$row['ra_mat_keterampilan_predikat']}}</td>
                <td>{{$row['ra_mat_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_ipa_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_ipa_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_ipa_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_ipa_keterampilan_nilai']}}</td>
                <td>{{$row['ra_ipa_keterampilan_predikat']}}</td>
                <td>{{$row['ra_ipa_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_ips_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_ips_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_ips_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_ips_keterampilan_nilai']}}</td>
                <td>{{$row['ra_ips_keterampilan_predikat']}}</td>
                <td>{{$row['ra_ips_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_big_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_big_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_big_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_big_keterampilan_nilai']}}</td>
                <td>{{$row['ra_big_keterampilan_predikat']}}</td>
                <td>{{$row['ra_big_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_bdy_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_bdy_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_bdy_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_bdy_keterampilan_nilai']}}</td>
                <td>{{$row['ra_bdy_keterampilan_predikat']}}</td>
                <td>{{$row['ra_bdy_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_org_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_org_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_org_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_org_keterampilan_nilai']}}</td>
                <td>{{$row['ra_org_keterampilan_predikat']}}</td>
                <td>{{$row['ra_org_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_pky_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_pky_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_pky_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_pky_keterampilan_nilai']}}</td>
                <td>{{$row['ra_pky_keterampilan_predikat']}}</td>
                <td>{{$row['ra_pky_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_jwa_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_jwa_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_jwa_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_jwa_keterampilan_nilai']}}</td>
                <td>{{$row['ra_jwa_keterampilan_predikat']}}</td>
                <td>{{$row['ra_jwa_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_man_pengetahuan_nilai']}}</td>
                <td>{{$row['ra_man_pengetahuan_predikat']}}</td>
                <td>{{$row['ra_man_pengetahuan_deskripsi']}}</td>
                <td>{{$row['ra_man_keterampilan_nilai']}}</td>
                <td>{{$row['ra_man_keterampilan_predikat']}}</td>
                <td>{{$row['ra_man_keterampilan_deskripsi']}}</td>
                <td>{{$row['ra_ekstra1_kegiatan']}}</td>
                <td>{{$row['ra_ekstra1_nilai']}}</td>
                <td>{{$row['ra_ekstra1_predikat']}}</td>
                <td>{{$row['ra_ekstra2_kegiatan']}}</td>
                <td>{{$row['ra_ekstra2_nilai']}}</td>
                <td>{{$row['ra_ekstra2_predikat']}}</td>
                <td>{{$row['ra_ekstra3_kegiatan']}}</td>
                <td>{{$row['ra_ekstra3_nilai']}}</td>
                <td>{{$row['ra_ekstra3_predikat']}}</td>
                <td>{{$row['ra_catatan_sakit']}}</td>
                <td>{{$row['ra_catatan_ijin']}}</td>
                <td>{{$row['ra_catatan_alpha']}}</td>
                <td>{{$row['ra_catatan_ayat']}}</td>
                <td>{{$row['ra_catatan_isi']}}</td>
                <td>{{$row['ra_catatan_pesan']}}</td>
            </tr>
        @endforeach
    </tbody>
</table>
