<?php

namespace App\Imports;

use App\RaporSisipan;
use Maatwebsite\Excel\Concerns\ToCollection;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\WithStartRow;
use Ramsey\Uuid\Uuid;
use App\Siswa;

class RaporSisipansImport implements ToCollection, WithStartRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    
    public function collection(Collection $rows)
    {   
        foreach ($rows as $row) 
        {
            $siswa = Siswa::where('s_nis',$row['0'])->value('id');
            if(!is_null($siswa)){
                $cekdata = null;
                $cekdata = RaporSisipan::where('siswa_id',$siswa)->where('periode_id', $this->rapor_id['periode'])->first();
                if(is_null($cekdata)){
                    RaporSisipan::create([
                        'id'  => Uuid::Uuid4(),
                        'siswa_id' => $siswa,
                        'periode_id' => $this->rapor_id['periode'],
                        'unit_id' =>  $this->rapor_id['unit'],
                        'user_id' =>  $this->rapor_id['user'],
                        'rs_tanggal' => null,
                        'rs_walikelas' => null,
                        'rs_spiritual_nilai' => null,
                        'rs_spiritual_predikat' => $row[11] ? $row[11]:null,
                        'rs_spiritual_deskripsi' => $row[12] ? $row[12]:null,
                        'rs_sosial_nilai' => null,
                        'rs_sosial_predikat' => $row[13] ? $row[13]:null,
                        'rs_sosial_deskripsi' => $row[14] ? $row[14]:null,
                        'rs_pak_uh1' => $row[15] ? $row[15]:null,
                        'rs_pak_uh2' => $row[16] ? $row[16]:null,
                        'rs_pak_uh3' => $row[17] ? $row[17]:null,
                        'rs_pak_tgs1' => $row[18] ? $row[18]:null,
                        'rs_pak_tgs2' => $row[19] ? $row[19]:null,
                        'rs_pak_tgs3' => $row[20] ? $row[20]:null,
                        'rs_pak_pts' => $row[21] ? $row[21]:null,
                        'rs_pak_prk' => $row[22] ? $row[22]:null,
                        'rs_pak_prd' => $row[23] ? $row[23]:null,
                        'rs_pak_pry' => $row[24] ? $row[24]:null,
                        'rs_pkn_uh1' => $row[25] ? $row[25]:null,
                        'rs_pkn_uh2' => $row[26] ? $row[26]:null,
                        'rs_pkn_uh3' => $row[27] ? $row[27]:null,
                        'rs_pkn_tgs1' => $row[28] ? $row[28]:null,
                        'rs_pkn_tgs2' => $row[29] ? $row[29]:null,
                        'rs_pkn_tgs3' => $row[30] ? $row[30]:null,
                        'rs_pkn_pts' => $row[31] ? $row[31]:null,
                        'rs_pkn_prk' => $row[32] ? $row[32]:null,
                        'rs_pkn_prd' => $row[33] ? $row[33]:null,
                        'rs_pkn_pry' => $row[34] ? $row[34]:null,
                        'rs_bin_uh1' => $row[35] ? $row[35]:null,
                        'rs_bin_uh2' => $row[36] ? $row[36]:null,
                        'rs_bin_uh3' => $row[37] ? $row[37]:null,
                        'rs_bin_tgs1' => $row[38] ? $row[38]:null,
                        'rs_bin_tgs2' => $row[39] ? $row[39]:null,
                        'rs_bin_tgs3' => $row[40] ? $row[40]:null,
                        'rs_bin_pts' => $row[41] ? $row[41]:null,
                        'rs_bin_prk' => $row[42] ? $row[42]:null,
                        'rs_bin_prd' => $row[43] ? $row[43]:null,
                        'rs_bin_pry' => $row[44] ? $row[44]:null,
                        'rs_mat_uh1' => $row[45] ? $row[45]:null,
                        'rs_mat_uh2' => $row[46] ? $row[46]:null,
                        'rs_mat_uh3' => $row[47] ? $row[47]:null,
                        'rs_mat_tgs1' => $row[48] ? $row[48]:null,
                        'rs_mat_tgs2' => $row[49] ? $row[49]:null,
                        'rs_mat_tgs3' => $row[50] ? $row[50]:null,
                        'rs_mat_pts' => $row[51] ? $row[51]:null,
                        'rs_mat_prk' => $row[52] ? $row[52]:null,
                        'rs_mat_prd' => $row[53] ? $row[53]:null,
                        'rs_mat_pry' => $row[54] ? $row[54]:null,
                        'rs_big_uh1' => $row[55] ? $row[55]:null,
                        'rs_big_uh2' => $row[56] ? $row[56]:null,
                        'rs_big_uh3' => $row[57] ? $row[57]:null,
                        'rs_big_tgs1' => $row[58] ? $row[58]:null,
                        'rs_big_tgs2' => $row[59] ? $row[59]:null,
                        'rs_big_tgs3' => $row[60] ? $row[60]:null,
                        'rs_big_pts' => $row[61] ? $row[61]:null,
                        'rs_big_prk' => $row[62] ? $row[62]:null,
                        'rs_big_prd' => $row[63] ? $row[63]:null,
                        'rs_big_pry' => $row[64] ? $row[64]:null,
                        'rs_bio_uh1' => $row[65] ? $row[65]:null,
                        'rs_bio_uh2' => $row[66] ? $row[66]:null,
                        'rs_bio_uh3' => $row[67] ? $row[67]:null,
                        'rs_bio_tgs1' => $row[68] ? $row[68]:null,
                        'rs_bio_tgs2' => $row[69] ? $row[69]:null,
                        'rs_bio_tgs3' => $row[70] ? $row[70]:null,
                        'rs_bio_pts' => $row[71] ? $row[71]:null,
                        'rs_bio_prk' => $row[72] ? $row[72]:null,
                        'rs_bio_prd' => $row[73] ? $row[73]:null,
                        'rs_bio_pry' => $row[74] ? $row[74]:null,
                        'rs_fis_uh1' => $row[75] ? $row[75]:null,
                        'rs_fis_uh2' => $row[76] ? $row[76]:null,
                        'rs_fis_uh3' => $row[77] ? $row[77]:null,
                        'rs_fis_tgs1' => $row[78] ? $row[78]:null,
                        'rs_fis_tgs2' => $row[79] ? $row[79]:null,
                        'rs_fis_tgs3' => $row[80] ? $row[80]:null,
                        'rs_fis_pts' => $row[81] ? $row[81]:null,
                        'rs_fis_prk' => $row[82] ? $row[82]:null,
                        'rs_fis_prd' => $row[83] ? $row[83]:null,
                        'rs_fis_pry' => $row[84] ? $row[84]:null,
                        'rs_eko_uh1' => $row[85] ? $row[85]:null,
                        'rs_eko_uh2' => $row[86] ? $row[86]:null,
                        'rs_eko_uh3' => $row[87] ? $row[87]:null,
                        'rs_eko_tgs1' => $row[88] ? $row[88]:null,
                        'rs_eko_tgs2' => $row[89] ? $row[89]:null,
                        'rs_eko_tgs3' => $row[90] ? $row[90]:null,
                        'rs_eko_pts' => $row[91] ? $row[91]:null,
                        'rs_eko_prk' => $row[92] ? $row[92]:null,
                        'rs_eko_prd' => $row[93] ? $row[93]:null,
                        'rs_eko_pry' => $row[94] ? $row[94]:null,
                        'rs_geo_uh1' => $row[95] ? $row[95]:null,
                        'rs_geo_uh2' => $row[96] ? $row[96]:null,
                        'rs_geo_uh3' => $row[97] ? $row[97]:null,
                        'rs_geo_tgs1' => $row[98] ? $row[98]:null,
                        'rs_geo_tgs2' => $row[99] ? $row[99]:null,
                        'rs_geo_tgs3' => $row[100] ? $row[100]:null,
                        'rs_geo_pts' => $row[101] ? $row[101]:null,
                        'rs_geo_prk' => $row[102] ? $row[102]:null,
                        'rs_geo_prd' => $row[103] ? $row[103]:null,
                        'rs_geo_pry' => $row[104] ? $row[104]:null,
                        'rs_sej_uh1' => $row[105] ? $row[105]:null,
                        'rs_sej_uh2' => $row[106] ? $row[106]:null,
                        'rs_sej_uh3' => $row[107] ? $row[107]:null,
                        'rs_sej_tgs1' => $row[108] ? $row[108]:null,
                        'rs_sej_tgs2' => $row[109] ? $row[109]:null,
                        'rs_sej_tgs3' => $row[110] ? $row[110]:null,
                        'rs_sej_pts' => $row[111] ? $row[111]:null,
                        'rs_sej_prk' => $row[112] ? $row[112]:null,
                        'rs_sej_prd' => $row[113] ? $row[113]:null,
                        'rs_sej_pry' => $row[114] ? $row[114]:null,
                        'rs_snr_uh1' => $row[115] ? $row[115]:null,
                        'rs_snr_uh2' => $row[116] ? $row[116]:null,
                        'rs_snr_uh3' => $row[117] ? $row[117]:null,
                        'rs_snr_tgs1' => $row[118] ? $row[118]:null,
                        'rs_snr_tgs2' => $row[119] ? $row[119]:null,
                        'rs_snr_tgs3' => $row[120] ? $row[120]:null,
                        'rs_snr_pts' => $row[121] ? $row[121]:null,
                        'rs_snr_prk' => $row[122] ? $row[122]:null,
                        'rs_snr_prd' => $row[123] ? $row[123]:null,
                        'rs_snr_pry' => $row[124] ? $row[124]:null,
                        'rs_snm_uh1' => $row[125] ? $row[125]:null,
                        'rs_snm_uh2' => $row[126] ? $row[126]:null,
                        'rs_snm_uh3' => $row[127] ? $row[127]:null,
                        'rs_snm_tgs1' => $row[128] ? $row[128]:null,
                        'rs_snm_tgs2' => $row[129] ? $row[129]:null,
                        'rs_snm_tgs3' => $row[130] ? $row[130]:null,
                        'rs_snm_pts' => $row[131] ? $row[131]:null,
                        'rs_snm_prk' => $row[132] ? $row[132]:null,
                        'rs_snm_prd' => $row[133] ? $row[133]:null,
                        'rs_snm_pry' => $row[134] ? $row[134]:null,
                        'rs_org_uh1' => $row[135] ? $row[135]:null,
                        'rs_org_uh2' => $row[136] ? $row[136]:null,
                        'rs_org_uh3' => $row[137] ? $row[137]:null,
                        'rs_org_tgs1' => $row[138] ? $row[138]:null,
                        'rs_org_tgs2' => $row[139] ? $row[139]:null,
                        'rs_org_tgs3' => $row[140] ? $row[140]:null,
                        'rs_org_pts' => $row[141] ? $row[141]:null,
                        'rs_org_prk' => $row[142] ? $row[142]:null,
                        'rs_org_prd' => $row[143] ? $row[143]:null,
                        'rs_org_pry' => $row[144] ? $row[144]:null,
                        'rs_pky_uh1' => $row[145] ? $row[145]:null,
                        'rs_pky_uh2' => $row[146] ? $row[146]:null,
                        'rs_pky_uh3' => $row[147] ? $row[147]:null,
                        'rs_pky_tgs1' => $row[148] ? $row[148]:null,
                        'rs_pky_tgs2' => $row[149] ? $row[149]:null,
                        'rs_pky_tgs3' => $row[150] ? $row[150]:null,
                        'rs_pky_pts' => $row[151] ? $row[151]:null,
                        'rs_pky_prk' => $row[152] ? $row[152]:null,
                        'rs_pky_prd' => $row[153] ? $row[153]:null,
                        'rs_pky_pry' => $row[154] ? $row[154]:null,
                        'rs_jwa_uh1' => $row[155] ? $row[155]:null,
                        'rs_jwa_uh2' => $row[156] ? $row[156]:null,
                        'rs_jwa_uh3' => $row[157] ? $row[157]:null,
                        'rs_jwa_tgs1' => $row[158] ? $row[158]:null,
                        'rs_jwa_tgs2' => $row[159] ? $row[159]:null,
                        'rs_jwa_tgs3' => $row[160] ? $row[160]:null,
                        'rs_jwa_pts' => $row[161] ? $row[161]:null,
                        'rs_jwa_prk' => $row[162] ? $row[162]:null,
                        'rs_jwa_prd' => $row[163] ? $row[163]:null,
                        'rs_jwa_pry' => $row[164] ? $row[164]:null,
                        'rs_man_uh1' => $row[165] ? $row[165]:null,
                        'rs_man_uh2' => $row[166] ? $row[166]:null,
                        'rs_man_uh3' => $row[167] ? $row[167]:null,
                        'rs_man_tgs1' => $row[168] ? $row[168]:null,
                        'rs_man_tgs2' => $row[169] ? $row[169]:null,
                        'rs_man_tgs3' => $row[170] ? $row[170]:null,
                        'rs_man_pts' => $row[171] ? $row[171]:null,
                        'rs_man_prk' => $row[172] ? $row[172]:null,
                        'rs_man_prd' => $row[173] ? $row[173]:null,
                        'rs_man_pry' => $row[174] ? $row[174]:null,
                        'rs_absensi_sakit' => $row[175] ? $row[175]:null,
                        'rs_absensi_ijin' => $row[176] ? $row[176]:null,
                        'rs_absensi_alpha' => $row[177] ? $row[177]:null,
                        'rs_catatan_ayat' => $row[178] ? $row[178]:null,
                        'rs_catatan_isi' => $row[179] ? $row[179]:null,
                        'rs_catatan_pesan' => $row[180] ? $row[180]:null,
                    ]);
                } else {
                    $cekdata->update([
                        'rs_tanggal' => null,
                        'rs_walikelas' => null,
                        'rs_spiritual_nilai' => null,
                        'rs_spiritual_predikat' => $row[11],
                        'rs_spiritual_deskripsi' => $row[12],
                        'rs_sosial_nilai' => null,
                        'rs_sosial_predikat' => $row[13],
                        'rs_sosial_deskripsi' => $row[14],
                        'rs_pak_uh1' => $row[15],
                        'rs_pak_uh2' => $row[16],
                        'rs_pak_uh3' => $row[17],
                        'rs_pak_tgs1' => $row[18],
                        'rs_pak_tgs2' => $row[19],
                        'rs_pak_tgs3' => $row[20],
                        'rs_pak_pts' => $row[21],
                        'rs_pak_prk' => $row[22],
                        'rs_pak_prd' => $row[23],
                        'rs_pak_pry' => $row[24],
                        'rs_pkn_uh1' => $row[25],
                        'rs_pkn_uh2' => $row[26],
                        'rs_pkn_uh3' => $row[27],
                        'rs_pkn_tgs1' => $row[28],
                        'rs_pkn_tgs2' => $row[29],
                        'rs_pkn_tgs3' => $row[30],
                        'rs_pkn_pts' => $row[31],
                        'rs_pkn_prk' => $row[32],
                        'rs_pkn_prd' => $row[33],
                        'rs_pkn_pry' => $row[34],
                        'rs_bin_uh1' => $row[35],
                        'rs_bin_uh2' => $row[36],
                        'rs_bin_uh3' => $row[37],
                        'rs_bin_tgs1' => $row[38],
                        'rs_bin_tgs2' => $row[39],
                        'rs_bin_tgs3' => $row[40],
                        'rs_bin_pts' => $row[41],
                        'rs_bin_prk' => $row[42],
                        'rs_bin_prd' => $row[43],
                        'rs_bin_pry' => $row[44],
                        'rs_mat_uh1' => $row[45],
                        'rs_mat_uh2' => $row[46],
                        'rs_mat_uh3' => $row[47],
                        'rs_mat_tgs1' => $row[48],
                        'rs_mat_tgs2' => $row[49],
                        'rs_mat_tgs3' => $row[50],
                        'rs_mat_pts' => $row[51],
                        'rs_mat_prk' => $row[52],
                        'rs_mat_prd' => $row[53],
                        'rs_mat_pry' => $row[54],
                        'rs_big_uh1' => $row[55],
                        'rs_big_uh2' => $row[56],
                        'rs_big_uh3' => $row[57],
                        'rs_big_tgs1' => $row[58],
                        'rs_big_tgs2' => $row[59],
                        'rs_big_tgs3' => $row[60],
                        'rs_big_pts' => $row[61],
                        'rs_big_prk' => $row[62],
                        'rs_big_prd' => $row[63],
                        'rs_big_pry' => $row[64],
                        'rs_bio_uh1' => $row[65],
                        'rs_bio_uh2' => $row[66],
                        'rs_bio_uh3' => $row[67],
                        'rs_bio_tgs1' => $row[68],
                        'rs_bio_tgs2' => $row[69],
                        'rs_bio_tgs3' => $row[70],
                        'rs_bio_pts' => $row[71],
                        'rs_bio_prk' => $row[72],
                        'rs_bio_prd' => $row[73],
                        'rs_bio_pry' => $row[74],
                        'rs_fis_uh1' => $row[75],
                        'rs_fis_uh2' => $row[76],
                        'rs_fis_uh3' => $row[77],
                        'rs_fis_tgs1' => $row[78],
                        'rs_fis_tgs2' => $row[79],
                        'rs_fis_tgs3' => $row[80],
                        'rs_fis_pts' => $row[81],
                        'rs_fis_prk' => $row[82],
                        'rs_fis_prd' => $row[83],
                        'rs_fis_pry' => $row[84],
                        'rs_eko_uh1' => $row[85],
                        'rs_eko_uh2' => $row[86],
                        'rs_eko_uh3' => $row[87],
                        'rs_eko_tgs1' => $row[88],
                        'rs_eko_tgs2' => $row[89],
                        'rs_eko_tgs3' => $row[90],
                        'rs_eko_pts' => $row[91],
                        'rs_eko_prk' => $row[92],
                        'rs_eko_prd' => $row[93],
                        'rs_eko_pry' => $row[94],
                        'rs_geo_uh1' => $row[95],
                        'rs_geo_uh2' => $row[96],
                        'rs_geo_uh3' => $row[97],
                        'rs_geo_tgs1' => $row[98],
                        'rs_geo_tgs2' => $row[99],
                        'rs_geo_tgs3' => $row[100],
                        'rs_geo_pts' => $row[101],
                        'rs_geo_prk' => $row[102],
                        'rs_geo_prd' => $row[103],
                        'rs_geo_pry' => $row[104],
                        'rs_sej_uh1' => $row[105],
                        'rs_sej_uh2' => $row[106],
                        'rs_sej_uh3' => $row[107],
                        'rs_sej_tgs1' => $row[108],
                        'rs_sej_tgs2' => $row[109],
                        'rs_sej_tgs3' => $row[110],
                        'rs_sej_pts' => $row[111],
                        'rs_sej_prk' => $row[112],
                        'rs_sej_prd' => $row[113],
                        'rs_sej_pry' => $row[114],
                        'rs_snr_uh1' => $row[115],
                        'rs_snr_uh2' => $row[116],
                        'rs_snr_uh3' => $row[117],
                        'rs_snr_tgs1' => $row[118],
                        'rs_snr_tgs2' => $row[119],
                        'rs_snr_tgs3' => $row[120],
                        'rs_snr_pts' => $row[121],
                        'rs_snr_prk' => $row[122],
                        'rs_snr_prd' => $row[123],
                        'rs_snr_pry' => $row[124],
                        'rs_snm_uh1' => $row[125],
                        'rs_snm_uh2' => $row[126],
                        'rs_snm_uh3' => $row[127],
                        'rs_snm_tgs1' => $row[128],
                        'rs_snm_tgs2' => $row[129],
                        'rs_snm_tgs3' => $row[130],
                        'rs_snm_pts' => $row[131],
                        'rs_snm_prk' => $row[132],
                        'rs_snm_prd' => $row[133],
                        'rs_snm_pry' => $row[134],
                        'rs_org_uh1' => $row[135],
                        'rs_org_uh2' => $row[136],
                        'rs_org_uh3' => $row[137],
                        'rs_org_tgs1' => $row[138],
                        'rs_org_tgs2' => $row[139],
                        'rs_org_tgs3' => $row[140],
                        'rs_org_pts' => $row[141],
                        'rs_org_prk' => $row[142],
                        'rs_org_prd' => $row[143],
                        'rs_org_pry' => $row[144],
                        'rs_pky_uh1' => $row[145],
                        'rs_pky_uh2' => $row[146],
                        'rs_pky_uh3' => $row[147],
                        'rs_pky_tgs1' => $row[148],
                        'rs_pky_tgs2' => $row[149],
                        'rs_pky_tgs3' => $row[150],
                        'rs_pky_pts' => $row[151],
                        'rs_pky_prk' => $row[152],
                        'rs_pky_prd' => $row[153],
                        'rs_pky_pry' => $row[154],
                        'rs_jwa_uh1' => $row[155],
                        'rs_jwa_uh2' => $row[156],
                        'rs_jwa_uh3' => $row[157],
                        'rs_jwa_tgs1' => $row[158],
                        'rs_jwa_tgs2' => $row[159],
                        'rs_jwa_tgs3' => $row[160],
                        'rs_jwa_pts' => $row[161],
                        'rs_jwa_prk' => $row[162],
                        'rs_jwa_prd' => $row[163],
                        'rs_jwa_pry' => $row[164],
                        'rs_man_uh1' => $row[165],
                        'rs_man_uh2' => $row[166],
                        'rs_man_uh3' => $row[167],
                        'rs_man_tgs1' => $row[168],
                        'rs_man_tgs2' => $row[169],
                        'rs_man_tgs3' => $row[170],
                        'rs_man_pts' => $row[171],
                        'rs_man_prk' => $row[172],
                        'rs_man_prd' => $row[173],
                        'rs_man_pry' => $row[174],
                        'rs_absensi_sakit' => $row[175],
                        'rs_absensi_ijin' => $row[176],
                        'rs_absensi_alpha' => $row[177],
                        'rs_catatan_ayat' => $row[178],
                        'rs_catatan_isi' => $row[179],
                        'rs_catatan_pesan' => $row[180]]);
                }
                
                $siswa = null;
            }
            
        }
    }

    public function startRow(): int
    {
        return 2;
    }

    public function  __construct($rapor_id)
    {
        $this->rapor_id= $rapor_id;
    }
}
